name: kubernetes CI
on:
  push:
    branches:
      - main

jobs:
  pyapp-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -t nbhardwaj/gha-pyapp:$GITHUB_SHA .  
    